export const XP_REWARDS = {
  COMPLETE_LESSON: 10,
  COMPLETE_QUIZ: 30,
  QUIZ_PERFECT_BONUS: 20,
  COMPLETE_MODULE: 100,
  COMPLETE_SIMULATION: 40,
  SIMULATION_PERFECT_BONUS: 15,
  DAILY_STREAK: 5,
  DAILY_STREAK_7_PLUS: 10,
} as const